version: '3.7'
services:
  DataAug:
    build: .
    privileged: true
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - /data:/data
    image: 'nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04'
    stdin_open: true
    tty: true
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]